$node = "ubuntu-02"

Vagrant.configure("2") do |config|
  config.vm.hostname = "#$node"
  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
    v.cpus = 2
    v.gui = false
    v.name = "#$node"
    v.linked_clone = true
  end
  config.vm.box = "bento/ubuntu-21.04"
#  config.vm.network "private_network", type: "dhcp", 
#    virtualbox__intnet: "NatNetwork"
#  config.vm.provision "shell", inline: <<-SHELL
#    CHEF_LICENSE=accept >> /etc/profile.d/chef.sh
#  SHELL
#  config.vm.provision "chef_client" do |chef|
#    chef.chef_server_url = "https://api.chef.io/organizations/snohio"
#    chef.validation_key_path = "C:\\Users\\butler\\.chef\\snohio-validator.pem"
#    chef.node_name = "#$node"
#    chef.delete_node = true
#    chef.delete_client = true
#  end
end
